<?php

return array (
  'name' => '888管理平台',
  'beian' => '粤ICP备15000000号-1',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
    'usend' => 'en-us',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'zifu' => 'Zifu',
    'cai' => 'WinGo',
    'big' => 'BigGame',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'green1379' => '2.00',
  'green5' => '1.5',
  'red2468' => '2.00',
  'red0' => '1.5',
  'number0-9' => '9.00',
  'violet05' => '4.5',
  'addmoneymin' => '600',
  'reducemoneymin' => '600',
  'award' => '0',
  'award2' => '0',
  'reg_award' => '0',
  'service_charge' => '0',
  'tax' => '0',
  'user_fan' => '0.2',
  'user_fan_1' => '0.8',
  'user_fan_2' => '0.4',
  'pay_memberid' => '200899694',
  'key' => 'f67lr0en4lw54p8kkpoejmircj8sjawm',
  'bankcode' => '961',
  'big' => '2.00',
  'small' => '2.00',
  'odd' => '2.00',
  'even' => '2.00',
  'bbig' => '2.00',
  'bsmall' => '2.00',
  'bodd' => '2.00',
  'beven' => '2.00',
  'bbigodd' => '4.00',
  'bbigeven' => '4.00',
  'bsmallodd' => '4.00',
  'bsmalleven' => '4.00',
  'kong' => '1',
  'app_url' => 'https://www.baidu.com/',
  'logo' => '/uploads/20231019/fb907a57e32a0d3d4f26767b1ca04fd1.jpeg',
  'web_name' => '红绿',
  'bet_min' => '10',
  'bet_max' => '100000',
  'fee' => '2',
  'verification_switch' => '0',
);